services:
  # Mysql as a main storage
  db:
    restart: always
    image: mysql
    container_name: uks_hub_db
    volumes:
      - ./mysqldata:/var/lib/mysql
    ports:
      - "8001:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=uks_hub
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - MYSQL_HOST=db

  # Django application
  # To run with image from dockerhub uncomment image action and comment build action
  # Run with "docker-compose up --build --force-recreate" to recreate container from remote image
  web:
    # image: djolewalker/ukshub # Uncomment this to build from remote docker image
    container_name: uks_hub_web
    labels:
      com.example.service: "web"
      com.example.description: "Use for the main web process"
    build: . # Comment this to build from remote docker image
    command: ["./scripts/wait_for_mysql.sh"]
    expose:
      - 8000
    volumes:
      - ./static:/code/static # must be same as nginx!
      - gitolite-git:/code/git-repos
      - public-key:/root/.ssh
    depends_on:
      - db
    links:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=UksHub.settings.test
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - MYSQL_HOST=db

  # Nginx as a web server and reverse proxy
  nginx:
    image: nginx
    container_name: uks_hub_nginx
    ports:
      - "8083:8083"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./static:/code/static #must be same as web!
    depends_on:
      - web

  # redis as a Django cache store
  redis:
    image: redis
    container_name: uks_hub_redis
    expose:
      - 6379

  git-server:
    image: jgiannuzzi/gitolite
    restart: always
    container_name: git-server
    depends_on:
      - git-deamon
      - git-http
      - web
    ports:
      - "2222:22"
    expose:
      - 22
    volumes:
      - gitolite-git:/var/lib/git/repositories
      - ./scripts/gitolite-entrypoint.sh:/docker-entrypoint.sh
      - public-key:/tmp/ssh-keys
    environment:
      - SSH_KEY=/tmp/ssh-keys/id_rsa.pub
      - SSH_KEY_NAME=random.user.admin

  git-deamon:
    build: ./git-deamon
    container_name: git-deamon
    ports:
      - "9418:9418"
    volumes:
      - gitolite-git:/var/lib/git

  git-http:
    image: ynohat/git-http-backend
    container_name: git-http
    expose:
      - 80
    volumes:
      - gitolite-git:/git

volumes:
  gitolite-sshkeys:
  gitolite-git:
  public-key: